- [Back_Tracking_Explained](https://medium.com/@andreaiacono/backtracking-explained-7450d6ef9e1a)
- [top-20-backtracking-algorithm-interview-questions](https://www.geeksforgeeks.org/top-20-backtracking-algorithm-interview-questions/)

# General pattern in Backtracking

- In back tracking you are looking for all the solution state. Now it's kind of a `n-way` tree. From each solution state you can go to some `k` child nodes. 
- That's why in backtracking we see `recursion` call inside a `for loop`. 
- And after the `for loop` there will be a backtracking step to come back to the previous node for rerouting the search direction to the `sibling` 

In [30]:
import numpy as np

# Permutaiton of a String

In [6]:
def permutation(s,start:int, end:int):
    if start == end:
        print("".join(s))
    for i in range(start, end):
        s[start], s[i] = s[i], s[start]
        permutation(s,start+1, end)
        s[start], s[i] = s[i], s[start] # backtrack

s = "ABC"
s = list(s)
n = len(s)
permutation(s,0,n)

ABC
ACB
BAC
BCA
CBA
CAB


# Rat Maze

## Idea:

Here we have 2 types of move (x+1, y) and (x,y+1). Now we could have done like

```py
for move in moves:
    x, y = move.x, move.y
    if safe(x,y):
        sol[x][y] = 1
        if rat_maze(moves[:]): reutn True
        sol[x][y] = 0
        return False
```
However intead of using the `for loop` we have used the 2 moves in the `if condition` inside

In [34]:
def is_safe(x :int, y:int, maze, n):
    
    if x>=0 and x<n and y>=0 and y<n and maze[x][y] == 1:
        return True
    else:
        return False

def solve_maze_util(maze, sol, x:int, y:int, n:int):
    
    if x == n - 1 and y == n - 1: 
        sol[x][y] = 1
        return True
    
    if is_safe(x,y,maze, n):
        
        sol[x][y] = 1
        
        if solve_maze_util(maze, sol, x+1, y, n): return True
        if solve_maze_util(maze, sol, x, y+1, n): return True
        
        # back track
        sol[x][y] = 0
        
    
    return False

def solve_maze(maze):
    n = len(maze)
    sol = [[0 for i in range(n)] for j in range(n)]
    
    res = solve_maze_util(maze, sol, 0 , 0, n)
    
    print(np.array(sol))
    return res

In [33]:
maze = [[1, 0, 0, 0], 
        [1, 1, 0, 1], 
        [0, 1, 0, 0], 
        [1, 1, 1, 1]]
solve_maze(maze)

[[1 0 0 0]
 [1 1 0 0]
 [0 1 0 0]
 [0 1 1 1]]


True

# Sudoku 